### ISSUE TITLE
changement de la photo des articles

### ISSUE THREAD

**Issue by GuyliannEngels** [kenmogne3/rabiole-kenmogne-blog#1]
Salut @kenmogne3 , 

hier tu m'as envoyé un mail pour me faire part d'un problème que tu as eu lors de la rédaction de ton post pour le cours d'anglais. Je vais employer les issue afin de t'aider. 

Une fois que tu as la réponse à ta question, tu peux fermer cette issue.

**Comment by GuyliannEngels** [comment]
je peux voir dans ton fichier article-1.Rmd que tu as réalisé des modifications qui ne se trouvent pas sur ton site web en ligne. 

N'oublie pas que tu dois compiler ton article (Knit) puis construire ton site (buid website), ensuite réaliser un commit et enfin faire ton push.

Concernant la photo que tu souhaite utiliser comme preview de ton article, il y a un souci.
Tu mets comme URL : https://www.earth.com/news/alternate-day-fasting/ Cependant ce lien renvoie vers un site web et non une photo. Quelle image souhaites tu vraiment employer ?

**Comment by kenmogne3** [comment]
Enfin j'ai trouvé! je souhaite mettre la photo d'un couvert avec une horloge à l intérieur ce qui matérialisera bien mon premier article qui est celui du jeun alterné.

**Comment by kenmogne3** [comment]
pour les modifications j'ai déja fait un build website mais je vais le refaire et voir ce que ca donne

**Comment by kenmogne3** [comment]
youpiiiiiiiiiiii ! c'est fait j ai réussi merci monsieur ss trop contente et en meme temps très fatiguée. merci encore bonne nuit

**Comment by GuyliannEngels** [comment]
Bravo @kenmogne3
