### ISSUE TITLE
mon article n apparait pas sur mon blog

### ISSUE THREAD

**Issue by kenmogne3** [kenmogne3/rabiole-kenmogne-blog#5]
bonjour monsieur j ai redigé mon article depuis la semaine passé mais quand je le poste sur mon blog je ne le vois pas je ne sais pas pourquoi

**Comment by GuyliannEngels** [comment]
Salut @kenmogne3 ,

Pour commencer tu ne dois pas oublier de me notifier quand tu me poses une question comme cela

```
@GuyliannEngels 
```

**Comment by GuyliannEngels** [comment]
petite question, 

@kenmogne3 après avoir rédigé tes deux articles, est ce que tu les as compilé (cliquer sur le bouton knit pour cela)?

**Comment by kenmogne3** [comment]
oui

**Comment by kenmogne3** [comment]
j ai enregistré, compiler, et constrius. apres construction mon article je le vois dans view mais je ne le vois pas dans mon blog

**Comment by kenmogne3** [comment]
@GuyliannEngels j ai enregistré, compiler, et constrius. apres construction mon article je le vois dans view mais je ne le vois pas dans mon blog

**Comment by GuyliannEngels** [comment]
C'est surprenant. 
Je vais tenter de débugger ton site à distance. Tu devras faire un pull apres pour récuperer mes modifcations éventuelle

**Comment by GuyliannEngels** [comment]
Dans le dossier _posts tu as 4 articles en cours d'édition, quelles sont les bons et les mauvais articles la dedans ?

**Comment by GuyliannEngels** [comment]
J'ai normalement corrigé plusieurs bugs. 

- Premier problème 
Concernant les fichiers dans les dossiers  : _posts/2019-11-01-molecule-links-weight-gain-to-gut-bacteria/  et /_posts/2019-11-01-molecule-links-weight-gain-to-gut-bacteria1/

J'ai ajouté l'argument `draft: true` dans le préambule des fichiers RMD comme cela tes articles sont considéré comme étant en cours d'édition.

2. Deuxième problème

Concernant les fichiers dans le dossier _posts/2019-10-23-article-2/

tu ne pouvais plus compiler ton document RMD car tu avais "cassé" le préambule du fichier. Un préambule débute par 3 tirets et se termine par 3 tirets 

- troisième problème

J'ai déplacé un fichier .R que dont la présence me semble étrange dans un dossier other

ps: n'oublie pas de faire ton pull et de ternir compte de mes remarques
