### ISSUE TITLE
verification par le prof si le devoir d'anglais a été bien fait

### ISSUE THREAD

**Issue by kenmogne3** [kenmogne3/rabiole-kenmogne-blog#6]

**Comment by GuyliannEngels** [comment]
@kenmogne3 ,

Tu as une question à me poser ? tu ne m'as pas posé de question dans la discussion et tu ne m'as ni assigné, ni cité dans un commentaire avec une question claire. 

Peux tu formuler dans les commentaires une question claire et précise en notifiant

**Comment by kenmogne3** [comment]
@GuyliannEngels bonjour monsieur, comme dois je faire pour supprimer miscellanous?

**Comment by kenmogne3** [comment]
j ai pas pu supprimer son contenu par contre j ai reussi à poster ce que je fais en anglais hors mis mes cours sous forme d article

**Comment by kenmogne3** [comment]
@GuyliannEngels j ai pas pu supprimer son contenu par contre j ai reussi à poster ce que je fais en anglais hors mis mes cours sous forme d article

**Comment by GuyliannEngels** [comment]
@kenmogne3 , tu dois simplement modifier le fichier _site.yml

voici le ton fichier 

![Capture d’écran 2019-11-06 à 08 41 35](https://user-images.githubusercontent.com/33956170/68278479-b1a66d00-0071-11ea-82fe-320520c82e45.png)

et voici le fichier du blog exemple 

![Capture d’écran 2019-11-06 à 08 41 53](https://user-images.githubusercontent.com/33956170/68278489-b703b780-0071-11ea-889a-1a2dbb8d0ee2.png)

tu vois la modification que tu dois y apporter ?

**Comment by kenmogne3** [comment]
@GuyliannEngels pas tres bien

**Comment by GuyliannEngels** [comment]
regarde bien avec attention ta ligne 8 et 9 et tente de retrouver ces lignes sur mon fichier ?

**Comment by kenmogne3** [comment]
ok

**Comment by kenmogne3** [comment]
@GuyliannEngels ok

**Comment by GuyliannEngels** [comment]
@kenmogne3 , tu vois que chez moi elle n'y sont plus. 
J'ai donc retirer la section miscellaneous de mon site. Tu peux faire de même

**Comment by kenmogne3** [comment]
@GuyliannEngels merci
